#!/usr/bin/env bash

nginx_conf="/etc/nginx/nginx.conf"
default_config="/etc/nginx/sites-available/default"

chmod 777 "$nginx_conf"
sed -i "s/80/8080/g" "$default_config"
sed -i "s/#user www-data/user nginx/" "$nginx_conf"
pkill -9 apache
su nginx -c "service nginx restart"

